name: Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test
        run: mvn -B package --file pom.xml

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build -t takeoff123/cicd-monitor:latest .
          docker push takeoff123/cicd-monitor:latest

      - name: Deploy to Server
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull takeoff123/cicd-monitor:latest
            docker stop cicd-monitor || true
            docker rm cicd-monitor || true
            docker run -d --name cicd-monitor -p 8080:8080
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/devopsboard_docker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
              -e SPRING_DATASOURCE_USERNAME=root
              -e SPRING_DATASOURCE_PASSWORD=root
              -e SPRING_MAIL_USERNAME=vinaybobby1122@gmail.com
              -e SPRING_MAIL_PASSWORD=fxvjruyamrhwcflw
              -e github.webhook.secret=${{ secrets.WEBHOOK_SECRET }}
              -e jwt.secret=${{ secrets.JWT_SECRET }}
              takeoff123/cicd-monitor:latest